export const eventsListButtons = [
  { title: 'Знаешь крутое мероприятие города?', button: 'поделись с другими', color: true },
  { title: 'Хочешь организовать встречу друзей?', button: 'действуй', color: false },
];

export const eventsListCards = [
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'events',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'events',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'world',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: '',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'meeting',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'meeting',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'events',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: '',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'meeting',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'events',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'world',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: '',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'world',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: true,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'world',
  },
  {
    title: 'спорт укрепляет здоровье игра в бейсбол между командами города',
    img: 'https://img.tourister.ru/files/2/4/2/7/6/0/3/0/original.jpg',
    checked: false,
    data: '5 сентября',
    sort: 'встречи',
    sort2: 'world',
  },
]